# Generated by Django 3.2.3 on 2021-05-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='view',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
    ]
