# Generated by Django 3.2.3 on 2021-05-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_question_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='view',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
    ]
